prevent dialing addresses that we're listening on
libp2p/go-libp2p-swarm pull request #237
Opened 2021-02-08 09:07 UTC by marten-seemann

It's impossible to run two nodes on the same IP:port, so we know for sure that any dial to an address that we're listening on will fail (as the peer IDs won't match).
In practice, this will be most useful for preventing dials to localhost for nodes that are listening on the default port.

2021-02-08 09:25 UTC, vyzo reviewed
hopefully this wont break relay dialing; it shouldn't because it shouldn't show in interface addrs, but mind checking?

2021-02-08 15:30 UTC, willscott commented
can we reuse the [`filterKnownUndialables`](https://github.com/libp2p/go-libp2p-swarm/blob/master/swarm_dial.go#L437)  logic?

2021-02-08 19:51 UTC, Stebalien requested changes
We're already doing this on line 449. I think the issue is that we're _only_ filtering IP+TCP and need to adjust  line 443 to allow any address starting with an IP addr (not just length 2 ones).

2021-02-09 03:05 UTC, marten-seemann commented
@Stebalien You're right. I removed the check for length 2, as QUIC returns 3 protocols here: IPv{4,6}, UDP, QUIC.

2021-02-09 03:33 UTC, Stebalien approved these changes

2021-02-09 03:33 UTC, merged